# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
author:
  name: Your Name
  email: your-email@domain.com
description: > # this means to ignore newlines until "url:"
  Write an awesome description for your new site here.
baseurl: "/jekyll-theme-iota" # the subpath of your site, e.g. /blog/
url: "https://artlogic.github.io" # the base hostname & protocol for your site

license: > # the license for your site - optional
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
powered_by: false  # display the powered by and theme info in the footer

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE']
permalink: pretty

kramdown:
  input: GFM

theme: jekyll-theme-iota

# plugins - needed for gh pages demo
# should not be needed when when using the theme (I think...)
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
